### ISSUE TITLE
Help on compiling for Windows

### ISSUE THREAD

**Issue by arunwizz** [andre-martins/TurboParser#10]
Hi Andre, 

This is actually not an issue, instead i need a help.  I am trying to compile the parser on windows platform, but unable to do it with the instructions given. I am anyway not comfortable with working on windows, but our project requires us to use it on windows only. I tried on linux and it works without much effort. Is there any pre-copmpiled windows binaries? or some detailed steps to compile on winodws? 

Regards
Arun

**Comment by andre-martins** [comment]
Hi Arun,

Sorry, there is no detailed list of instructions. I know some people managed to compile on windows without great effort though...

Andre'
