### ISSUE TITLE
preposition collapsing

### ISSUE THREAD

**Issue by vaskonov** [andre-martins/TurboParser#12]
Hi andre-martins!

Thank you for the great product.

I wonder if it's possible to do preposition collapsing in TurboParser?
Preposition collapsing is when two consecutive edges of dependency collapse to one if they connected by a preposition.

Thank you.

**Comment by andre-martins** [comment]
Hi vaskonov,

You can do it easily as a post-processing step. That's currently not implemented in TurboParser, though.

Hope this helps,

Andre'
