### ISSUE TITLE
python binding: Segmentation fault

### ISSUE THREAD

**Issue by nournia** [andre-martins/TurboParser#13]
Hi,
I've trained TurboParser on Persian dependency treebank and successfully tested it with parsing new sentences. Using TurboParser executable with command line works properly but when I use python interface, this error occurs:

    Segmentation fault (core dumped)

Here is my input file:

    1	من	من	PRO	PRO	_	0	ROOT	_	_	
    2	به	به	P	P	_	0	ROOT	_	_	
    3	مدرسه	مدرسه	N	N	_	0	ROOT	_	_	
    4	رفته_بودم	رفته_بودم	V	V	_	0	ROOT	_	_	
    5	.	.	PUNC	PUNC	_	0	ROOT	_	_

**Comment by andre-martins** [comment]
Dear Alireza,

Can you please send me the full log?

Thanks,

André

2015-05-08 15:19 GMT+01:00 Alireza Nourian <notifications@github.com>:

**Comment by nournia** [comment]
Is it the complete log:

	I0508 23:44:18.345984 21697 Options.cpp:64] Setting --test=1
	I0508 23:44:18.346097 21697 DependencyOptions.cpp:232] Arc factored parts enabled.
	I0508 23:44:18.346115 21697 DependencyOptions.cpp:235] Consecutive sibling parts enabled.
	I0508 23:44:18.346127 21697 DependencyOptions.cpp:238] Grandparent parts enabled.
	I0508 23:44:18.346197 21697 TokenDictionary.cpp:59] Setting --form_case_sensitive=0
	I0508 23:44:18.346215 21697 TokenDictionary.cpp:69] Setting --prefix_length=4
	I0508 23:44:18.346227 21697 TokenDictionary.cpp:72] Setting --suffix_length=4
	I0508 23:44:18.393015 21697 DependencyOptions.cpp:146] Setting --model_type=standard
	I0508 23:44:18.393091 21697 DependencyOptions.cpp:149] Setting --large_feature_set=1
	I0508 23:44:18.393106 21697 DependencyOptions.cpp:152] Setting --labeled=1
	I0508 23:44:18.393118 21697 DependencyOptions.cpp:155] Setting --prune_labels=1
	I0508 23:44:18.393129 21697 DependencyOptions.cpp:158] Setting --prune_distances=1
	I0508 23:44:18.393141 21697 DependencyOptions.cpp:161] Setting --prune_basic=1
	I0508 23:44:18.393152 21697 DependencyOptions.cpp:164] Setting --pruner_posterior_threshold=0.0001
	I0508 23:44:18.393203 21697 DependencyOptions.cpp:168] Setting --pruner_max_heads=10
	I0508 23:44:18.393226 21697 DependencyOptions.cpp:232] Arc factored parts enabled.
	I0508 23:44:18.393237 21697 DependencyOptions.cpp:235] Consecutive sibling parts enabled.
	I0508 23:44:18.393249 21697 DependencyOptions.cpp:238] Grandparent parts enabled.
	I0508 23:44:56.359668 21697 SparseLabeledParameterVector.h:277] Statistics for labeled parameter vector:
	I0508 23:44:56.359789 21697 SparseLabeledParameterVector.h:278] Features with sparse labels: 12153947 Total: 12851555 Sparse labels: 19317389
	I0508 23:44:56.359807 21697 Parameters.cpp:32] Squared norm of the weight vector = 961.751
	I0508 23:44:56.359872 21697 Parameters.cpp:33] Number of features = 37010623
	I0508 23:44:57.125457 21697 SparseLabeledParameterVector.h:277] Statistics for labeled parameter vector:
	I0508 23:44:57.125555 21697 SparseLabeledParameterVector.h:278] Features with sparse labels: 0 Total: 0 Sparse labels: 0
	I0508 23:44:57.125571 21697 Parameters.cpp:32] Squared norm of the weight vector = 393.448
	I0508 23:44:57.125607 21697 Parameters.cpp:33] Number of features = 1767061
	I0508 23:44:57.125669 21697 TurboParserInterface.cpp:91] Took 38.779 sec.
	I0508 23:44:57.125720 21697 TurboParserInterface.cpp:130] Deleting tagger workers.
	I0508 23:44:57.125744 21697 TurboParserInterface.cpp:133] Deleting parser workers.
	I0508 23:44:57.125756 21697 TurboParserInterface.cpp:73] Deleting parser pipe.
	I0508 23:45:02.839110 21697 TurboParserInterface.cpp:75] Deleting parser options.
	I0508 23:45:03.044857 21697 TurboParserInterface.cpp:136] Clearing argument list.
	I0508 23:45:03.044975 21697 TurboParserInterface.cpp:139] Done.
	*** Error in `/usr/bin/python': free(): invalid pointer: 0x00007fd2b32720f8 ***
	Aborted (core dumped)

**Comment by andre-martins** [comment]
It's hard to tell what is going on from the log. Apparently the model was
loaded correctly but the parser was deleted shortly after. Can you please
send me:
1) the model file
2) the python script you used to call the parser
3) the sentence you were parsing?

Thanks.

Andre'

2015-05-08 20:15 GMT+01:00 Alireza Nourian <notifications@github.com>:

**Comment by nournia** [comment]
I've figured out what was wrong. This piece of code, causes error:

	import turboparser
	interface = turboparser.PTurboParser().create_parser()
	interface.load_parser_model(model_file)

And with some little changes, everything works:

	import turboparser
	_interface = turboparser.PTurboParser()
	interface = _interface.create_parser()
	interface.load_parser_model(model_file)

Thanks.
