### ISSUE TITLE
F0206 00:31:22.776695  7325 Alphabet.cpp:86] Check failed: success

### ISSUE THREAD

**Issue by paridhij** [andre-martins/TurboParser#23]
TurboTagger is working fine with the sample_tagger.model but when I use english_proj_tagger.model, the listed error pops. 

Here is the stacktrace:
root@INDXRCI01HC01:/home/paridhi/Soft/TurboParser-2.2.0/deps/local/lib# cd ..
root@INDXRCI01HC01:/home/paridhi/Soft/TurboParser-2.2.0/deps/local# cd ..
root@INDXRCI01HC01:/home/paridhi/Soft/TurboParser-2.2.0/deps# cd ..
root@INDXRCI01HC01:/home/paridhi/Soft/TurboParser-2.2.0#  ./TurboTagger --test \
> --evaluate \
> --file_model=models/english_proj/english_proj_tagger.model \
> --file_test=data/sample/sample_test.conll.tagging \
> --file_prediction=data/sample/sample_test.conll.tagging.predicted \
> --logtostderr
I0206 00:31:22.772121  7325 TurboTagger.cpp:33] Running tagger...
I0206 00:31:22.772306  7325 TokenDictionary.cpp:59] Setting --form_case_sensitive=2
I0206 00:31:22.772318  7325 TokenDictionary.cpp:69] Setting --prefix_length=18838
I0206 00:31:22.772323  7325 TokenDictionary.cpp:72] Setting --suffix_length=925892608
F0206 00:31:22.776695  7325 Alphabet.cpp:86] Check failed: success
*** Check failure stack trace: ***
    @     0x7fd61413e04d  google::LogMessage::Fail()
    @     0x7fd61413fed5  google::LogMessage::SendToLog()
    @     0x7fd61413dc5b  google::LogMessage::Flush()
    @     0x7fd61414080e  google::LogMessageFatal::~LogMessageFatal()
    @           0x423503  Alphabet::Load()
    @           0x419cd7  TokenDictionary::Load()
    @           0x414c9d  SequencePipe::LoadModel()
    @           0x425bf1  Pipe::LoadModelByName()
    @           0x422c22  TestTagger()
    @           0x403072  main
    @     0x7fd61356fec5  (unknown)
    @           0x40360d  (unknown)
Aborted (core dumped)

**Comment by andre-martins** [comment]
Hi,

It looks like there is a mismatch between the pre-trained model you are
using and the version of TurboParser (which seems to be 2.2.0). You can go
to http://www.cs.cmu.edu/~ark/TurboParser/ and download the latest version
(2.3.0) and the corresponding tagger model.

André

2016-02-05 11:24 GMT+00:00 paridhij <notifications@github.com>:

**Comment by paridhij** [comment]
With the new version 2.3.0, the error now says at SequencePipe.cpp- "The model file is too old and not supported anymore. " Any clues on where the updated model is?

**Comment by paridhij** [comment]
With the new version 2.3.0, the error now says at SequencePipe.cpp- "The model file is too old and not supported anymore. " Any clues on where the updated model is?

**Comment by andre-martins** [comment]
Yes, it's provided in the TurboParser page:
http://www.cs.cmu.edu/~ark/TurboParser/.

The link is this:
http://www.cs.cmu.edu/~ark/TurboParser/sample_models/english_proj_tagger.tar.gz
.

André

2016-02-07 18:11 GMT+00:00 paridhij <notifications@github.com>:

**Comment by paridhij** [comment]
I suppose I am unable to run TurboTagger itself. TurboParser gives me a whole set of new errors. Log attached

paridhi@INDXRCI01HC01:~/Soft/TurboParser-2.3.0$ export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`pwd;`/deps/local/lib:"
paridhi@INDXRCI01HC01:~/Soft/TurboParser-2.3.0$ echo "I solved the problem with statistics." | ./scripts/parse.sh
F0208 08:06:31.942383  1413 SequencePipe.cpp:53] Check failed: model_check == kSequenceModelCheck (3458764513825363458 vs. 1234567890) The model file is too old and not supported anymore.
*** Check failure stack trace: ***
    @     0x7fd786d0004d  google::LogMessage::Fail()
    @     0x7fd786d01ed5  google::LogMessage::SendToLog()
    @     0x7fd786cffc5b  google::LogMessage::Flush()
    @     0x7fd786d0280e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4155f7  SequencePipe::LoadModel()
    @           0x425541  Pipe::LoadModelByName()
    @           0x42ef22  TestTagger()
    @           0x4036a2  main
    @     0x7fd786131ec5  (unknown)
    @           0x40374f  (unknown)
/home/paridhi/Soft/TurboParser-2.3.0/scripts/run_tagger.sh: line 26:  1413 Aborted                 (core dumped) ${path_bin}/TurboTagger --test --file_model=${file_model} --file_test=${file_test} --file_prediction=${file_prediction}
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
Use of uninitialized value $line_tagging in split at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 18.
Use of uninitialized value $cpos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
Use of uninitialized value $pos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
Use of uninitialized value $line_tagging in split at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 18.
Use of uninitialized value $cpos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
Use of uninitialized value $pos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
Use of uninitialized value $line_tagging in split at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 18.
Use of uninitialized value $cpos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
Use of uninitialized value $pos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
Use of uninitialized value $line_tagging in split at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 18.
Use of uninitialized value $cpos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
Use of uninitialized value $pos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
Use of uninitialized value $line_tagging in split at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 18.
Use of uninitialized value $cpos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
Use of uninitialized value $pos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
Use of uninitialized value $line_tagging in split at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 18.
Use of uninitialized value $cpos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
Use of uninitialized value $pos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
Use of uninitialized value $line_tagging in split at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 18.
Use of uninitialized value $cpos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
Use of uninitialized value $pos in concatenation (.) or string at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 32.
readline() on closed filehandle TAGGING at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 9.
Use of uninitialized value $line_tagging in scalar chomp at /home/paridhi/Soft/TurboParser-2.3.0/scripts/create_conll_predicted_tags_corpus.pl line 11.
/home/paridhi/Soft/TurboParser-2.3.0/scripts/run_parser.sh: line 33:  1424 Segmentation fault      (core dumped) ${path_bin}/TurboParser --test --evaluate --file_model=${file_model} --file_test=${file_test} --file_prediction=${file_prediction}

**Comment by andre-martins** [comment]
Are you sure you are using the model in
http://www.cs.cmu.edu/~ark/TurboParser/sample_models/english_proj_tagger.tar.gz?
The error you described is still triggered by an old model file.

2016-02-07 18:45 GMT+00:00 paridhij <notifications@github.com>:

**Comment by paridhij** [comment]
Yes, it worked now. I got the package via browser than the wget. Thanks!!
