### ISSUE TITLE
Segmentation fault with Python version

### ISSUE THREAD

**Issue by delanoe** [andre-martins/TurboParser#27]
Hello,
using the Python version, both 2.7 and 3.4 and 3.5 have the same bug:
using the example:
> import nlp_pipeline
is ok (I have adapted the paths for the imports and the print function for Python 3 versions)

>pipe = nlp_pipeline.NLPPipeline()
is ok

> print pipe.parse_conll('I solved the problem with statistics.', 'EN')
raise a "segmentation fault" which is hard to debug, even with strace.
segmentation fault  ipython2 (or ipython3 with 3.4, 3.5)

Do you have any idea how to debug it please ?

Thanks in advance for your help and of course for this great lib!

**Comment by andre-martins** [comment]
Hi Alexandre,

It may have to do with loading the model. Can you send me the logs?

André

2016-04-19 15:48 GMT+01:00 Alexandre Delanoë <notifications@github.com>:

**Comment by delanoe** [comment]
Hi Andre,
That is the issue: I have no log, just 'segmentation error'. Which logs are thinking about ?

**Comment by delanoe** [comment]
Ok, You were right for the models.

I have added the models as suggested in the README (train sessions).

F0419 18:46:22.441820 21550 Pipe.cpp:60] Check failed: fs Could not open model file for reading: /opt/TurboParser/models/english_proj/english_proj_tagger.model

may I change the path ?

**Comment by delanoe** [comment]
And I had a old version of model (format has changed). So it works fine with python 2.7. Still a bug with python 3.* but it is not really a bug.

You may close the issue. Many thanks for your reply :)

**Comment by andre-martins** [comment]
Great that it worked out!
